# Generated by Django 5.0.3 on 2024-04-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
    ]
