# Generated by Django 5.0.3 on 2024-04-07 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_about_me_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+60123456789'. Up to 10 digits allowed.", regex='^\\+?60?\\d{9,10}$')]),
        ),
    ]
