# Generated by Django 5.0.3 on 2024-04-13 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Whatsapp number must be entered in the format: '+60123456789'. Wth country code +60 and up to 10 digits allowed.", regex='^\\+?60?\\d{9,10}$')]),
        ),
    ]
