# Generated by Django 5.0.3 on 2024-04-13 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_whatsapp_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+60123456789'. With country code +60 and up to 10 digits allowed.", regex='^\\+?60?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, default=6011223341, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+60123456789'. With country code +60 and up to 10 digits allowed.", regex='^\\+?60?\\d{9,10}$')]),
            preserve_default=False,
        ),
    ]
