# Generated by Django 5.0.3 on 2024-04-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
