# Generated by Django 5.0.3 on 2024-04-25 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_body_message_text_remove_message_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
