# Generated by Django 5.0.3 on 2024-03-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageBox',
            new_name='Message',
        ),
    ]
