# Generated by Django 5.0.2 on 2024-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_desc', models.CharField(max_length=200)),
                ('service_price', models.IntegerField()),
            ],
        ),
    ]
