# Generated by Django 5.0.3 on 2024-03-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_item_image_service_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='item_image',
            new_name='service_image',
        ),
    ]
