# Generated by Django 5.0.3 on 2024-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_item_image_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(default='https://neurosoft.com/img/notfound.png', max_length=500, upload_to=''),
        ),
    ]
