# Generated by Django 5.0.3 on 2024-04-29 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_service_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='service_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
