# Generated by Django 5.0.2 on 2024-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://talentclick.com/wp-content/uploads/2021/08/placeholder-image.png', max_length=500),
        ),
    ]
