# Generated by Django 5.0.2 on 2024-03-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.AdmjRGdGsTp_sN_njYJTYwHaE8?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
