# Generated by Django 5.0.2 on 2024-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R.01caacbe38240d12ae9a7f7ccce2a50a?rik=JO7Kwss5SP6ANQ&riu=http%3a%2f%2fwww.dunbarbagpipes.com%2fsite_templates%2fdunbar12-20-2016%2fximagenotavailable.png&ehk=6ft%2fms%2frvSQffThmGvV64b%2bV5SlFulKHK245iAk2u9Q%3d&risl=&pid=ImgRaw&r=0', max_length=500),
        ),
    ]
