# Generated by Django 5.0.3 on 2024-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('SO', 'Sold')], default='AV', max_length=2),
        ),
    ]
