# Generated by Django 5.0.3 on 2024-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://neurosoft.com/img/notfound.png', upload_to='images_item'),
        ),
    ]
