# Generated by Django 5.0.3 on 2024-03-11 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='item_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
