# Generated by Django 5.0.3 on 2024-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=250),
        ),
    ]
