# Generated by Django 5.0.3 on 2024-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
