# Generated by Django 5.0.3 on 2024-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_alter_item_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_detail',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
