# Generated by Django 5.0.3 on 2024-04-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
